### ISSUE TITLE
Unable to broadcast in Chrome or Edge

### ISSUE THREAD

**Issue by Skizu** [zelloptt/zello-channel-api#126]
I am unable to broadcast messages in Chrome or Edge using JS SDK on both Windows and MacOS. I have confirmed this in our use of the SDK and via [examples/02-player-recorder.html](https://github.com/zelloptt/zello-channel-api/blob/master/sdks/js/examples/02-player-recorder.html).

## Exception
```
Uncaught (in promise) DOMException: Failed to execute ‘postMessage’ on ‘DedicatedWorkerGlobalScope’: ArrayBuffer is not detachable and could not be cloned.
    at OggOpusEncoder.segmentPacket (webpack-internal:///./src/encoderWorker.js:345:30)
    at OggOpusEncoder.encode (webpack-internal:///./src/encoderWorker.js:134:12)
    at eval (webpack-internal:///./src/encoderWorker.js:13:19)
```

## MacOS Browser
| Info | Details |
| ------------- | ------------- |
| Browser | **Chrome** |
| Browser Version | **88.0.4324.150 (Official Build) (x86_64)** |
| OS | **MacOS** |
| OS Version | **11.2.1 (20D74)** |

**Comment by vocoded** [comment]
Hi Daniel, thanks for the report.  Alex may have been in touch earlier - we're investigating and will provide updates as we have them.

**Comment by daniel-drakontas** [comment]
Resolved by https://github.com/zelloptt/zello-channel-api/pull/128.

**Comment by Skizu** [comment]
Resolved by https://github.com/zelloptt/zello-channel-api/pull/128.
